name: Modify Permissions

on:
  workflow_dispatch:
    
permissions:
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run simple command
        run: |
          echo "Hello World"
